use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-CT_Example' do
  pod 'MKLoRaWAN-CT', :path => '../'

  target 'MKLoRaWAN-CT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
